# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
ElementwiseSub = B - C
print("Subtraktion:", ElementwiseSub)

print('-------------------------------')

ElementwiseMulti = B * C
print("Multiplikation\n", ElementwiseMulti)

print('-------------------------------')

MatrixMulti = B @ C
print("Matrix multiplikation:\n", MatrixMulti)

Subtraktion: [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
-------------------------------
Multiplikation
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
-------------------------------
Matrix multiplikation:
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
ExponentiateOfD = np.exp(D)
print("Exponent av D:\n", ExponentiateOfD)

print('-------------------------------')

print("Minsta värdet i matrisen:\n", D.min())

print('-------------------------------')

print("Minsta värdet i alla rader:\n", D.min(axis=1))

print('-------------------------------')

print("Minsta värdet i alla kolumner:\n", D.min(axis=0))

print('-------------------------------')

LowestIndexValueMatrix = np.argmin(D)
print("Index värde för lägsta i matris:\n", LowestIndexValueMatrix)

print('-------------------------------')

LowestIndexValueForMinValuePerRow = np.argmin(D, axis=1)
print("Index värde för lägsta värde i varje rad\n", LowestIndexValueForMinValuePerRow)

print('-------------------------------')

print("Summan av alla element\n", D.sum())

print('-------------------------------')

print("Medelvärdet av för varje kolumn\n", D.mean(axis=0))

print('-------------------------------')

MedianForEachColumn = np.median(D, axis=0)
print("Median för varje kolumn\n", MedianForEachColumn)

Exponent av D:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
-------------------------------
Minsta värdet i matrisen:
 1
-------------------------------
Minsta värdet i alla rader:
 [1 4 7]
-------------------------------
Minsta värdet i alla kolumner:
 [1 2 3]
-------------------------------
Index värde för lägsta i matris:
 0
-------------------------------
Index värde för lägsta värde i varje rad
 [0 0 0]
-------------------------------
Summan av alla element
 45
-------------------------------
Medelvärdet av för varje kolumn
 [4. 5. 6.]
-------------------------------
Median för varje kolumn
 [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [8]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [10]:
'That you only will print out the row with index 1 as an array'

'That you only will print out the row with index 1 as an array'

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [11]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [13]:
for x in np.nditer(A):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [14]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [15]:
"Since b has three axes means that it is a three dimensional array" 
"The code starts by creating a onedimensional array, a. and then reshapes it into a 3 dimensional array b."
"When it reshapes it creates 2 blocks with three rows in each, the -1 means that it should figure out the last on which would be 5 kolumns per row"

'When it reshapes it creates 2 blocks with three rows in each, the -1 means that it should figure out the last on which would be 5 kolumns per row'

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [16]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [17]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [18]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [19]:
def add_mult_matrices(A, B, operation):
    if not isinstance(A, np.ndarray) or not isinstance(B, np.ndarray):
        raise TypeError("Both inputs must be numpy.ndarray")

    if operation not in ("add", "multiply"):
        raise ValueError("Operation must be either 'add' or 'multiply'")

    if operation == "add":
        if A.shape != B.shape:
            raise ValueError("For addition, matrices must have the same shape")
        return A + B

    if operation == "multiply":
        if A.shape[1] != B.shape[0]:
            raise ValueError(
                "For multiplication, number of columns in A must equal number of rows in B"
            )
        return A @ B

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [20]:
x = np.array([[4, 3]])
print("a:\n", x.shape)

print("b:\n", 5*x)

print("c:\n", 3*x)

calculate_d = add_mult_matrices(5*x, 3*x, "add")
print("d:\n", calculate_d)

print("e:\n", 8*x)

calculate_f = add_mult_matrices(4*x, -1*x, "add")
print("f:\n", calculate_f)

print("g:\n", x.T)

print("h: I guess No since they will end up having different shapes")

print("i:\n", np.linalg.norm(x))


a:
 (1, 2)
b:
 [[20 15]]
c:
 [[12  9]]
d:
 [[32 24]]
e:
 [[32 24]]
f:
 [[12  9]]
g:
 [[4]
 [3]]
h: I guess No since they will end up having different shapes
i:
 5.0


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [21]:
A = np.array([[ 2,  1, -1],
              [ 1, -1,  1]])

B = np.array([[ 4, -2,  1],
              [ 2, -4, -2]])

C = np.array([[1, 2],
              [2, 1]])

D = np.array([[3, 4],
              [4, 3]])

E = np.array([[1],
              [2]])

I = np.array([[1, 0],
              [0, 1]])

print("a:\n", 2*A)

print("b:\n", B - 2*A)

print("c:\n", "Different shapes so not defined")

print("d:\n", 2*D - 3*C)

print("e:\n", D.T + 2*D)

print("f:\n", 2*C.T - 2*D.T)

print("g:\n", "Different shapes so not defined")

print("h:\n", "Different shapes so not defined")

print("i:\n", C*D)

print("h:\n", "Different sizes so not defined")

print("k:\n", C*I)

print("h:\n", "Different sizes so not defined")



a:
 [[ 4  2 -2]
 [ 2 -2  2]]
b:
 [[ 0 -4  3]
 [ 0 -2 -4]]
c:
 Different shapes so not defined
d:
 [[3 2]
 [2 3]]
e:
 [[ 9 12]
 [12  9]]
f:
 [[-4 -4]
 [-4 -4]]
g:
 Different shapes so not defined
h:
 Different shapes so not defined
i:
 [[3 8]
 [8 3]]
h:
 Different sizes so not defined
k:
 [[1 0]
 [0 1]]
h:
 Different sizes so not defined


### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [22]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [23]:
v2isv1 = v2.base is v1

if v2isv1:
    print("v2 is a view of v1")
else:
    print("v2 is a copy")

print("Changing the last element i v2 will also change the last element in v1. This since they share the same memory")


v2 is a view of v1
Changing the last element i v2 will also change the last element in v1. This since they share the same memory
